'use client';

import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { autoGenerateDraftPlans } from '@/app/actions/stowage-plan';
import styles from './page.module.css';

export default function AutoGenerateButton() {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [result, setResult] = useState<{
    type: 'success' | 'error';
    message: string;
    details?: { voyageNumber: string; action: string; reason?: string; planNumber?: string }[];
  } | null>(null);

  const handleClick = () => {
    setResult(null);
    startTransition(async () => {
      const res = await autoGenerateDraftPlans();
      if (res.success) {
        const created = res.created ?? 0;
        setResult({
          type: 'success',
          message: res.message ?? '',
          details: res.results,
        });
        if (created > 0) {
          router.refresh();
        }
      } else {
        setResult({ type: 'error', message: res.error ?? 'Unknown error' });
      }
    });
  };

  return (
    <div className={styles.autoGenWrap}>
      <button
        className={styles.btnAutoGen}
        onClick={handleClick}
        disabled={isPending}
        title="Create draft plans for voyages departing within 28 days that have confirmed bookings"
      >
        {isPending ? 'Generating…' : '⚡ Auto-Generate Plans'}
      </button>

      {result && (
        <div className={`${styles.autoGenToast} ${result.type === 'error' ? styles.autoGenToastError : result.details?.some(d => d.action === 'created') ? styles.autoGenToastSuccess : styles.autoGenToastNeutral}`}>
          <p className={styles.autoGenToastMsg}>{result.message}</p>
          {result.details && result.details.length > 0 && (
            <ul className={styles.autoGenList}>
              {result.details.map((d, i) => (
                <li key={i} className={d.action === 'created' ? styles.autoGenCreated : styles.autoGenSkipped}>
                  <span className={styles.autoGenVoyage}>{d.voyageNumber}</span>
                  {d.action === 'created'
                    ? <span>→ {d.planNumber}</span>
                    : <span className={styles.autoGenReason}>{d.reason}</span>
                  }
                </li>
              ))}
            </ul>
          )}
          <button className={styles.autoGenDismiss} onClick={() => setResult(null)}>✕</button>
        </div>
      )}
    </div>
  );
}
