'use client';

import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { autoGenerateDraftPlans } from '@/app/actions/stowage-plan';
import styles from './page.module.css';

type DetailItem = {
  voyageNumber: string;
  action: 'CREATED' | 'UPDATED' | 'SKIPPED';
  reason?: string;
  bookingsUsed: number;
  contractEstimatesUsed: number;
  conflictCount: number;
  sectionsAssigned: number;
};

export default function AutoGenerateButton() {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [result, setResult] = useState<{
    type: 'success' | 'error';
    message: string;
    created?: number;
    updated?: number;
    skipped?: number;
    details?: DetailItem[];
  } | null>(null);

  const handleClick = () => {
    setResult(null);
    startTransition(async () => {
      const res = await autoGenerateDraftPlans();
      if (res.success) {
        const changed = (res.created ?? 0) + (res.updated ?? 0);
        setResult({
          type: 'success',
          message: res.message ?? '',
          created: res.created,
          updated: res.updated,
          skipped: res.skipped,
          details: res.details as DetailItem[] | undefined,
        });
        if (changed > 0) {
          router.refresh();
        }
      } else {
        setResult({ type: 'error', message: (res as any).error ?? 'Unknown error' });
      }
    });
  };

  const hasChanges = (result?.created ?? 0) + (result?.updated ?? 0) > 0;

  return (
    <div className={styles.autoGenWrap}>
      <button
        className={styles.btnAutoGen}
        onClick={handleClick}
        disabled={isPending}
        title="Create or update draft plans for voyages departing within 60 days using bookings and contract estimates"
      >
        {isPending ? 'Generating…' : '⚡ Auto-Generate Plans'}
      </button>

      {result && (
        <div className={`${styles.autoGenToast} ${
          result.type === 'error'
            ? styles.autoGenToastError
            : hasChanges
              ? styles.autoGenToastSuccess
              : styles.autoGenToastNeutral
        }`}>
          <p className={styles.autoGenToastMsg}>{result.message}</p>

          {result.type === 'success' && (result.created !== undefined || result.updated !== undefined) && (
            <p className={styles.autoGenSummary}>
              {[
                result.created ? `${result.created} created` : '',
                result.updated ? `${result.updated} updated` : '',
                result.skipped ? `${result.skipped} skipped` : '',
              ].filter(Boolean).join(' · ')}
            </p>
          )}

          {result.details && result.details.length > 0 && (
            <ul className={styles.autoGenList}>
              {result.details.map((d, i) => (
                <li
                  key={i}
                  className={
                    d.action === 'CREATED'
                      ? styles.autoGenCreated
                      : d.action === 'UPDATED'
                        ? styles.autoGenUpdated
                        : styles.autoGenSkipped
                  }
                >
                  <span className={styles.autoGenVoyage}>{d.voyageNumber}</span>

                  {d.action === 'SKIPPED' ? (
                    <span className={styles.autoGenReason}>{d.reason}</span>
                  ) : (
                    <span className={styles.autoGenDetail}>
                      → {d.action === 'CREATED' ? 'Created' : 'Updated'}
                      {d.sectionsAssigned > 0 && ` · ${d.sectionsAssigned} sections`}
                      {(d.bookingsUsed > 0 || d.contractEstimatesUsed > 0) && (
                        <span className={styles.autoGenSources}>
                          {' '}({d.bookingsUsed > 0 ? `${d.bookingsUsed} booking${d.bookingsUsed > 1 ? 's' : ''}` : ''}
                          {d.bookingsUsed > 0 && d.contractEstimatesUsed > 0 ? ' + ' : ''}
                          {d.contractEstimatesUsed > 0 ? `${d.contractEstimatesUsed} estimate${d.contractEstimatesUsed > 1 ? 's' : ''}` : ''})
                        </span>
                      )}
                      {d.conflictCount > 0 && (
                        <span className={styles.autoGenConflicts}>
                          {' '}⚠ {d.conflictCount} conflict{d.conflictCount > 1 ? 's' : ''}
                        </span>
                      )}
                    </span>
                  )}
                </li>
              ))}
            </ul>
          )}

          <button className={styles.autoGenDismiss} onClick={() => setResult(null)}>✕</button>
        </div>
      )}
    </div>
  );
}
